run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gocritic
    - gofmt
    - misspell

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-tags:
      - style
      - experimental
      - opinionated

issues:
  exclude-dirs:
    - docs
    - deploy
