apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "ephor-scanner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ephor-scanner.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        {{- include "ephor-scanner.selectorLabels" . | nindent 8 }}
    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
      template:
        metadata:
          labels:
            {{- include "ephor-scanner.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          serviceAccountName: {{ include "ephor-scanner.serviceAccountName" . }}
          securityContext:
            fsGroup: 10001
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: scanner
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              envFrom:
                - configMapRef:
                    name: {{ include "ephor-scanner.fullname" . }}
                - secretRef:
                    name: {{ include "ephor-scanner.fullname" . }}
              volumeMounts:
                - name: trivy-cache
                  mountPath: {{ .Values.trivy.cacheDir }}
              {{- with .Values.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          volumes:
            - name: trivy-cache
              {{- if .Values.cache.enabled }}
              persistentVolumeClaim:
                claimName: {{ include "ephor-scanner.fullname" . }}-cache
              {{- else }}
              emptyDir: {}
              {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
