{{- if .Values.cache.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ephor-scanner.fullname" . }}-cache
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ephor-scanner.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.cache.accessMode }}
  {{- if .Values.cache.storageClass }}
  storageClassName: {{ .Values.cache.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.cache.size }}
{{- end }}
