apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ephor-scanner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ephor-scanner.labels" . | nindent 4 }}
type: Opaque
stringData:
  EPHOR_API_URL: {{ required "ephor.apiUrl is required" .Values.ephor.apiUrl | quote }}
  {{- if .Values.ephor.authHeader }}
  EPHOR_AUTH_HEADER: {{ .Values.ephor.authHeader | quote }}
  {{- end }}
  {{- if .Values.ephor.authValue }}
  EPHOR_AUTH_VALUE: {{ .Values.ephor.authValue | quote }}
  {{- end }}
